# ===== DATASOURCE (H2) =====
spring.datasource.url=jdbc:h2:mem:ticketdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# ===== H2 CONSOLE =====
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# Force data-dev.sql à s'exécuter après la création du schéma par Hibernate.
spring.jpa.defer-datasource-initialization=true

# ===== AUTO FEED =====
spring.sql.init.data-locations=classpath:data-dev.sql

# ===== JWT =====
# Indique à Spring Boot de charger le fichier .env comme un fichier properties
spring.config.import=optional:file:.env[.properties]
security.jwt.secret=${TICKETFLOW_JWT_SECRET}
# 30 minutes
security.jwt.expiration=1800000

# ===== SWAGGER ===== #
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationSorter=true
springdoc.swagger-ui.tagsSorter=true
springdoc.api-docs.resolve-schema-properties=true
springdoc.writer-with-order-by-keys=true
springdoc.swagger-ui.persistAuthorization=true