# ===== DATASOURCE (POSTGRES) =====
spring.datasource.url=jdbc:postgresql://localhost:5432/ticketdb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.h2.console.enabled=false

# ===== JWT =====
spring.config.import=optional:file:.env[.properties]
security.jwt.secret=${TICKETFLOW_JWT_SECRET}
# 30 minutes
security.jwt.expiration=1800000

# ===== SWAGGER ===== #
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationSorter=true
springdoc.swagger-ui.tagsSorter=true
springdoc.api-docs.resolve-schema-properties=true
springdoc.writer-with-order-by-keys=true
springdoc.swagger-ui.persistAuthorization=true