# ===== DATASOURCE (POSTGRES) =====
spring.datasource.url=jdbc:postgresql://localhost:5432/ticketdb

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=postgres

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.h2.console.enabled=false

# ===== JWT =====
security.jwt.secret=kbeeBkNp5WSA4TdXEHNi8HxQIKL1rDJM3IAy0L/MxxI=
# 30 minutes
security.jwt.expiration=1800000
