# ===== DATASOURCE (H2) =====
spring.datasource.url=jdbc:h2:mem:ticketdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.sql.init.mode=never

# ===== H2 CONSOLE =====
spring.h2.console.enabled=false

# ===== JWT =====
# Indique à Spring Boot de charger le fichier .env comme un fichier properties
spring.config.import=optional:file:.env[.properties]
security.jwt.secret=${TICKETFLOW_JWT_SECRET}
# access token : 15 min
security.jwt.expiration=900000
# 30 min  (glissant, lastUsedAt)
security.jwt.refresh.idle-timeout=1800000
# 8 h     (absolu, createdAt)
security.jwt.refresh.max-session=28800000
